name: Test Executable

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        sudo apt-get install -y wine64

    # Make build script executable and run it
    - name: Build
      run: |
        chmod +x build.sh
        ./build.sh

    # Run test
    - name: Test
      run: |
        wine ./algo.exe "input" --math


    - name: Package for Upload
      run: |
        mkdir release
        cp algo.exe release/
        cp glpk_4_65.dll release/
        cp -r input release/
    
    - name: Upload Package
      uses: actions/upload-artifact@v3
      with:
        name: exe-with-input
        path: release/
