name: Test Executable

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install MinGW cross-compiler
    - name: Install MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    # Make build script executable and run it
    - name: Build
      run: |
        chmod +x build.sh
        ./build.sh

    # Run test
    - name: Test
      run: |
        wine ./algo.exe "input" --math
